id: P63766657
initial_creation_type: input
source_metadata:
  title: Khenpo Shenpen Nangwa Series
  language: es
  description: 'Texts by and about the great scholar Khenpo Shenpen Nangwa (gzhan
    phan snang ba, 1871–1927) better known as Khenpo Shenga (mkhan po gzhan dga''):'
  volume:
    88d55c8ac6d0483ab5a847cc8b54f7db:
      title: Advice on Yidam Practice
      parent: Advice
    b4b73d8bd558427b8cec7e57ca89083c:
      title: Concise Middle Way Aspiration
      parent: Aspiration Prayers
    a1fa94b257154121b2c5c19770d20071:
      title: Middle Way Aspiration
      parent: Aspiration Prayers
    d399516d56a04b0481ba3ce5f9c0f682:
      title: 'Light on the Path of Liberation: The Life of the Second Buddha Vasubandhu'
      parent: Biography
    f59e8da214c6414db3df4553eceb3ff6:
      title: On the Yogācāra Treatises and Buddha Nature
      parent: Buddhist Philosophy
    2473fa0787ad43a09d6b85d38bf89a00:
      title: Prologue to Abhisamayālaṃkāra Commentary
      parent: Commentaries
    656ff04634a44fdfb9b0f17fe717c6fb:
      title: Prologue to Introduction to the Middle Way (Madhyamakāvatāra)
      parent: Commentaries
    6975d13992e4409aaeab88996232a923:
      title: The Three Noble Principles
      parent: Commentaries
    bfc89a2e25cf4e99aa56bb910b1ea1a1:
      title: In This Pure Awareness
      parent: Dzogchen
    09009c55c2824cb9b37259d861f86c59:
      title: Types of Spiritual Song
      parent: Miscellaneous
    b11857ce5ec34209924f172f2eae924d:
      title: Notes from Miscellaneous Writings
      parent: Notes
    93b8c034012e4decbfc96c8d84789093:
      title: In Praise of Longchenpa – The Greatness of the Omniscient Longchen Rabjam
      parent: Praise
    dc65aaf5bdf0458eb8dc112d17ffee5a:
      title: Praise of Candrakīrti
      parent: Praise
    2b1d8e0c34ce46f1ad1b6712c94c3872:
      title: Prayer to Invoke the Wisdom Mind of the Gentle Protector Sakya Paṇḍita
      parent: Prayers
    96d6000324c2418b94331ca64488ebca:
      title: A Song of Prayer to Jamyang Loter Wangpo
      parent: Songs
    47f288eeed544186a93b25677b43c426:
      title: 'Divine Music: Words of Encouragement for the Authentic Path'
      parent: Songs
created_at: '2022-03-01T00:28:36.704636'
last_modified_at: '2022-03-01T00:28:36.704639'
